### ISSUE TITLE
Gamma possibly incorrect

### ISSUE THREAD

**Issue by Frosty-J** [lyze237/gdx-TinyVG#3]
I'd like to test more graphics but have only semi-successfully converted the one as of yet. Compared with TVG's SDK renderer, there are holes in the thonk and it's much paler than it should be.

GIMP (SVG)|tvg-render (TVG)|gdx-TinyVG (TVG)
-|-|-
![](https://user-images.githubusercontent.com/60154347/148249799-32bad0af-53ee-4bb7-b989-a631d8e81418.png)|![](https://user-images.githubusercontent.com/60154347/148249812-dda1460d-26c1-46ba-b9f1-e3865148cc30.png)|![](https://user-images.githubusercontent.com/60154347/148249816-7bc00e33-474b-4653-b6c9-5db1d2234827.png)

Original SVG, TVG(T) and converted SVG: [pirate.zip](https://github.com/lyze237/gdx-TinyVG/files/7816570/pirate.zip)

**Comment by lyze237** [comment]
Thanks!
